name = "rss"
main = "src/index.ts"
compatibility_date = "2024-06-20"

# 可选：自定义 RSS 源 URL（通过环境变量）
[vars]
RSS_URLS = "https://www.xmhai.cn/rss.xml"

# 可选：自定义白名单
ALLOWED_ORIGINS=https://www.xmhai.cn

# 可选：配置自定义域名
# routes = [
#   { pattern = "rss.xmhai.cn", custom_domain = true }
# ]




[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
